config/routes.rb
Rails.application.routes.draw do
  resources :activities

  root 'activities#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
	extend SimpleCalendar
	has_calendar :attribute => :date

validates :address_start,  presence: true
validates :address_end, presence: true

geocoded_by :given_addressess
after_validation :geocode

	def given_addressess
		#Take address A, and return coordinates
		start_coordinates = Geocoder.coordinates(address_start)
		#Take address B, and return coordinates
		end_coordinates = Geocoder.coordinates(address_end)
		#Calculate distance in km, and save to database
		self.distance = Geocoder::Calculations.distance_between(start_coordinates, end_coordinates)
	end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @hash = Gmaps4rails.build_markers(@activities) do |activity, marker|
      marker.lat activity.latitude
      marker.lng activity.longitude
    end
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:address_start, :address_end, :latitude, :longitude, :lat_end, :long_end, :distance, :date)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :address_start %>
  </div>
  <div class="field">
    <%= f.text_field :address_end %>
  </div>
  <div class="field">
    <%= f.datetime_select :date %>
  </div>
  <div class="actions">
    <%= f.submit class: "success button"%>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<div class="row">
  <div class="small-10 small-centered columns">
    <%= column_chart Activity.group_by_day(:date, format: "%F").count %>
  </div>
</div>

<div class="row">
  <div class="small-10 small-centered columns">
    <h1>Total distance from each day of current month</h1>
    <table>
      <thead>
      <tr>
        <th>Day</th>
        <th>Total daily dist. [km]</th>
      </tr>
      </thead>
      <tbody>
      <%  Activity.group_by_day(:date, range: DateTime.now.in_time_zone.beginning_of_month..Time.now).sum(:distance).each do |day, activities| %>
          <tr>
            <td><%= day.strftime('%F') %> </td>
            <% if activities == 0 %>
                <td class="info round label"><%= activities.round(2)%> [km]</td>
            <% else %>
                <td class="success round label"><%= activities.round(2)%> [km]</td>
            <% end %>
      <% end %>
      </tr>
      </tbody>
    </table>
  </div>
</div>


<div class="row">
  <div class="small-10 small-centered columns">
    <h1>Calendar</h1>

    <%= month_calendar table: {class: "calendar"}, tr: {class: "calendar-row"}, td: {class: "day"}, events: @activities do |date, activities| %>
        <%= date %>

        <% activities.each do |activity| %>
            <div>
              <p class="success round label"><%= activity.distance.round(2) %> [km]</p>
            </div>
        <% end %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="small-10 small-centered columns">
    <h1>Your Stats</h1>

    <table>
      <thead>
      <tr>
        <th>Total dist. [km]</th>
        <th>Total dist. this year [km]</th>
        <th>Total dist. this month [km]</th>
        <th>Total dist. this week [km]</th>
        <th>Total dist. today [km]</th>
        <th>Average dist. [km]</th>
      </tr>
      </thead>

      <tbody>
      <tr>
        <td><%= @activities.sum(:distance).round(2) %></td>
        <td><%= @activities.where(date: Time.zone.now.all_year).sum(:distance).round(2) %></td>
        <td><%= @activities.where(date: Time.zone.now.all_month).sum(:distance).round(2) %></td>
        <td><%= @activities.where(date: Time.zone.now.all_week).sum(:distance).round(2) %></td>
        <td><%= @activities.where(date: Time.zone.now.all_day).sum(:distance).round(2) %></td>
        <td><%= @activities.average(:distance).round(2) %></td>
      </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="small-10 small-centered columns">
    <h1>Listing Activities by date</h1>

    <table>
      <thead>
      <tr>
        <th>Address start</th>
        <th>Address end</th>
        <th>Distance [km]</th>
        <th>Date</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @activities.order("date DESC").each do |activity| %>
          <tr>
            <td><%= activity.address_start %></td>
            <td><%= activity.address_end %></td>
            <td class="success round label"><%= activity.distance.round(2) %></td>
            <td><%= activity.date.to_formatted_s(:long) %></td>
            <td><%= link_to 'Show', activity %></td>
            <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
            <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <br>
  </div>
</div>

app/views/activities/new.html.erb
<div class="row">
  <div class="small-6 small-centered columns">
    <h1>New Activity</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/activities/show.html.erb
<div class="row">
  <div class="small-10 small-centered columns">
    <ul class="pricing-table">
      <li class="title"><%= @activity.address_start %> to <%= @activity.address_end %></li>
      <li class="price"><%= @activity.distance.round(2) %> km.</li>
      <li class="description"><%= @activity.date.to_formatted_s(:long) %></li>
      <li class="cta-button"><%= link_to 'Stats', activities_path, class: "success button" %></li>
    </ul>
  </div>

  <div class="row">
    <div class="small-10 small-centered columns">   
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Fitofit" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
    <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
    <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

    
  </head>

  <body>

    <nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to 'Fitofit', root_path %></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="active"><%= link_to 'Stats', activities_path %></li>
      <li class="active"><%= link_to 'New Activity', new_activity_path %></li>
    </ul>
  </section>
</nav>

<%= display_flash_messages %>

    <%= yield %>
  

  <footer class="row">

<div class="large-12 columns">
<hr/>
<div class="row">
<div class="large-6 columns">
<p>&copy; PT 2015</p>
</div>
<div class="large-6 columns">
<ul class="inline-list right">
<li><a href="https://github.com/paweltar">Github</a></li>
</ul>
</div>
</div>
</div>
</footer>
  </body>
</html>